cc_library(
    name = "CaesarCipher",
    srcs = ["CaesarCipher.cc"],
    hdrs = ["CaesarCipher.h"],
    deps = ["//libs/common:Common"],
    visibility = ["//main:__pkg__", "//test:__subpackages__"],
)